MyBoard/ViewModels/HomeViewModel.cs
using MyBoard.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBoard.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Product> favProduct { get; set; }
    }
}

MyBoard/ViewModels/ProductCartViewModel.cs
using MyBoard.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBoard.ViewModels
{
    public class ProductCartViewModel
    {
        public ProductCart productCart { get; set; }
    }
}

MyBoard/ViewModels/ProductListViewModel.cs
using MyBoard.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBoard.ViewModels
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> allProduct { get; set; }

        public string productCategory { get; set; }
    }
}

MyBoard/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyBoard.Data.Interfaces;
using MyBoard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBoard.Controllers
{
    public class HomeController : Controller
    {

        private readonly IAllProducts _prodRep;

        public HomeController(IAllProducts prodRep)
        {
            _prodRep = prodRep;
        }
        public ViewResult Index()
        {
            var homeProduct = new HomeViewModel
            {
                favProduct = _prodRep.getFavProd
            };

            return View(homeProduct);
        }
    }
}

MyBoard/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using MyBoard.Data.Interfaces;
using MyBoard.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBoard.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrder allOrder;
        private readonly ProductCart productCart;

        public OrderController(IAllOrder allOrder, ProductCart productCart)
        {
            this.allOrder = allOrder;
            this.productCart = productCart;
        }

        public IActionResult CheckOut()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CheckOut(Order order)
        {
            productCart.listCartItem = productCart.getCartItems();
            if(productCart.listCartItem.Count == 0)
            {
                ModelState.AddModelError("", "Ваша корзина пустая");
            }

            if (ModelState.IsValid)
            {
                allOrder.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

MyBoard/Controllers/ProductCartController.cs
using Microsoft.AspNetCore.Mvc;
using MyBoard.Data.Interfaces;
using MyBoard.Data.Models;
using MyBoard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBoard.Controllers
{
    public class ProductCartController : Controller
    {
        private readonly IAllProducts _prodRep;
        private readonly ProductCart _prodCart;

        public ProductCartController(IAllProducts prodRep, ProductCart prodCart)
        {
            _prodRep = prodRep;
            _prodCart = prodCart;
        }

        public ViewResult Index()
        {
            var items = _prodCart.getCartItems();
            _prodCart.listCartItem = items;

            var obj = new ProductCartViewModel
            {
                productCart = _prodCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _prodRep.Products.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _prodCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

MyBoard/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MyBoard.Data.Interfaces;
using MyBoard.Data.Models;
using MyBoard.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBoard.Controllers
{
    public class ProductController : Controller
    {
        private readonly IAllProducts _allProducts;
        private readonly IProductCategory _allCategories;

        public ProductController(IAllProducts iAllProducts, IProductCategory iProductCat)
        {
            _allProducts = iAllProducts;
            _allCategories = iProductCat;
        }
        [Route("Product/List")]
        [Route("Product/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products = null;
            string productCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                products = _allProducts.Products.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    products = _allProducts.Products.Where(i => i.Category.categoryName.Equals("электромобили"));
                    productCategory = "электромобили";
                }
                else 
                {
                    products = _allProducts.Products.Where(f => f.Category.categoryName.Equals("классическике"));
                    productCategory = "классическике";
                }

            }
            var prodObj = new ProductListViewModel 
            {
                allProduct = products,
                productCategory = productCategory
            };

            ViewBag.Title = "Страница с автомобилями";
            return View(prodObj);
        }
    }
}

MyBoard/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Лучшие товары</h1>

<div class="row mt-5 mb-2">
    @{
        foreach (Product product in Model.favProduct)
        {
            @Html.Partial("AllProducts", product)
        }
    }
</div>

MyBoard/Views/Order/CheckOut.cshtml
@model Order

<div class="row">
    <h3>Оформление Заказов</h3>
    <form asp-action="CheckOut" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-5">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="address"></label>
            <div class="col-md-5">
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Подтвердить заказ"/>
    </form>
</div>

MyBoard/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

MyBoard/Views/Product/List.cshtml
@model ProductListViewModel

    <h1>Все товары</h1>
    <h2>@Model.productCategory</h2>

    <div class="row mt-5 mb-2">
        @{
            foreach (Product product in Model.allProduct)
            {
                @Html.Partial("AllProducts", product)
            }

        }
    </div>

MyBoard/Views/ProductCart/Index.cshtml
@model ProductCartViewModel

<div class="container">
    @foreach (var el in Model.productCart.listCartItem)
    {
        <div class="alert alert-warning mt-3">
            <b>Автомобиль:</b>@el.product.name<br />
            <b>Цена:</b>@el.product.price.ToString("c")

        </div>
    }

    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="CheckOut">Оплатить</a>
</div>

MyBoard/Views/Shared/AllProducts.cshtml
@model Product

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>Модель: @Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ProductCart" asp-action="addToCart" asp-route-id="@Model.id">Добавить в корзину</a></p>
</div>

MyBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/css/style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">MyBoard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Product/List">Товары</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Product/List/electro">Электро</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Product/List/fuel">Классические</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="/ProductCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2022 MyBoard ·</p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>